# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c540f515af75a2b779a11c799c21044c576c3943045bf8204516d44c99d461771e8b0dd819b41b8be4bf20ec65ea891f8ecce86cfeb98bb32d3af85f613990aa

test:
  secret_key_base: 990c731845aaa297391caa2fe258a78242bd8fce8ee8b45ca07719e7ae6fb753657a72f88b8bbfa6e12ed0298ecaebba6e071bf0e08a4aecb45e90d3ac64b338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
